## Makefile for building wireshark.exe with Microsoft C and nmake
## Use: $(MAKE) /$(MAKEFLAGS) -f makefile.nmake
#
# $Id: Makefile.nmake 40763 2012-01-29 20:33:58Z etxrab $

include ..\..\config.nmake

CFLAGS=$(WARNINGS_ARE_ERRORS) -D_U_="" $(LOCAL_CFLAGS)

.c.obj::
   $(CC) $(CFLAGS) -Fd.\ -c $<

all : lemon.exe

clean:
	rm -f lemon.obj lemon.exe lemon.ilk *.pdb *.sbr lemon.exe.manifest

distclean: clean

maintainer-clean: distclean
